### ISSUE TITLE
Request: Break out HTML, JS, and CSS

### ISSUE THREAD

**Issue by andrewjrangel** [WeCanCode-Club/WeCanCode#2]
It would be a better practice to have the HTML, JS, and CSS be their own files. If someone could setup the project to properly break out these files it would help the project growth stay manageable.

**Comment by CerealNotFound** [comment]
I want to do that sir.

**Comment by andrewjrangel** [comment]
That would be great @CerealNotFound! Let me know if you have questions about forking the repository, making those changes, and then submitting a pull request. If you could create a descriptive name for your branch and have informative commit messages that will be helpful. I will work on a style guide for those.
