### ISSUE TITLE
Request : Create Logo for WeCanCode

### ISSUE THREAD

**Issue by yourventura** [WeCanCode-Club/WeCanCode#3]
WeCanCode Club is a super cool idea and deserves a super cool logo.

**Comment by andrewjrangel** [comment]
Thanks for the suggestion Ventura, we will start reaching out to people and see if we can come up with a great design!

**Comment by bmumz** [comment]
I can give it a whirl!

**Comment by andrewjrangel** [comment]
Great I have assigned it to you! Thanks, I am open with any questions you have
